export const mockUser = {
  id: 'mock-user-1',
  email: 'admin@example.com',
  name: 'Admin User',
  picture: 'https://ui-avatars.com/api/?name=Admin+User&background=0D8ABC&color=fff',
  createdAt: new Date().toISOString(),
  lastLoginAt: new Date().toISOString(),
};

export const mockApprovals = [
  {
    id: 'approval-1',
    reelId: 'reel-001',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/reel1/400/600',
    caption: '🌟 Amazing sunset views from the beach today! #sunset #beach #nature',
    hashtags: ['sunset', 'beach', 'nature', 'beautiful', 'photography'],
    musicTrack: 'Chill Vibes - Tropical House',
    scheduledFor: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(), // 2 hours from now
    status: 'pending',
    priority: 1,
    metadata: {
      duration: 15,
      resolution: '1080x1920',
      fileSize: 12500000,
      generatedBy: 'Luma AI',
    },
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'approval-2',
    reelId: 'reel-002',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/reel2/400/600',
    caption: '🔥 Daily workout motivation! Push your limits 💪 #fitness #motivation #gym',
    hashtags: ['fitness', 'motivation', 'gym', 'workout', 'health'],
    musicTrack: 'Epic Motivation - Workout Mix',
    scheduledFor: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    status: 'pending',
    priority: 2,
    metadata: {
      duration: 12,
      resolution: '1080x1920',
      fileSize: 10200000,
      generatedBy: 'Luma AI',
    },
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'approval-3',
    reelId: 'reel-003',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/reel3/400/600',
    caption: '✨ Dream big, work hard, stay focused! #inspiration #success #mindset',
    hashtags: ['inspiration', 'success', 'mindset', 'entrepreneur', 'goals'],
    musicTrack: 'Uplifting Piano',
    scheduledFor: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    status: 'pending',
    priority: 0,
    metadata: {
      duration: 18,
      resolution: '1080x1920',
      fileSize: 15800000,
      generatedBy: 'Luma AI',
    },
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'approval-4',
    reelId: 'reel-004',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/reel4/400/600',
    caption: '🌄 Morning coffee with this incredible view! #coffee #morning #travel',
    hashtags: ['coffee', 'morning', 'travel', 'lifestyle', 'adventure'],
    musicTrack: 'Acoustic Morning',
    status: 'approved',
    priority: 0,
    metadata: {
      duration: 14,
      resolution: '1080x1920',
      fileSize: 11900000,
      generatedBy: 'Luma AI',
    },
    reviewedBy: mockUser.id,
    reviewedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'approval-5',
    reelId: 'reel-005',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/reel5/400/600',
    caption: '🎨 Creative process behind the artwork #art #creative #design',
    hashtags: ['art', 'creative', 'design', 'artist', 'inspiration'],
    musicTrack: 'Lo-fi Beats',
    status: 'rejected',
    priority: 0,
    metadata: {
      duration: 16,
      resolution: '1080x1920',
      fileSize: 13400000,
      generatedBy: 'Luma AI',
    },
    reviewedBy: mockUser.id,
    reviewedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    rejectionReason: 'Quality not meeting standards, needs better lighting',
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockAccounts = [
  {
    id: 1,
    username: 'lifestyle_vibes',
    accountId: 'ig_account_123456',
    accessToken: 'mock_token_1',
    isActive: true,
    lastSyncAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    metadata: {
      followersCount: 45230,
      profilePictureUrl: 'https://ui-avatars.com/api/?name=Lifestyle+Vibes&background=E1306C&color=fff',
      biography: '✨ Lifestyle & Travel | 📍 Worldwide | DM for collabs',
    },
    createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
  {
    id: 2,
    username: 'fitness_motivation',
    accountId: 'ig_account_789012',
    accessToken: 'mock_token_2',
    isActive: true,
    lastSyncAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    metadata: {
      followersCount: 32100,
      profilePictureUrl: 'https://ui-avatars.com/api/?name=Fitness+Motivation&background=405DE6&color=fff',
      biography: '💪 Daily Workout Tips | 🏋️ Transform Your Body | Link in bio',
    },
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  {
    id: 3,
    username: 'creative_designs',
    accountId: 'ig_account_345678',
    accessToken: 'mock_token_3',
    isActive: false,
    lastSyncAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    metadata: {
      followersCount: 18500,
      profilePictureUrl: 'https://ui-avatars.com/api/?name=Creative+Designs&background=FD1D1D&color=fff',
      biography: '🎨 Designer | 🖌️ Creative Content | Shop: link below',
    },
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockNotifications = [
  {
    id: 'notif-1',
    userId: mockUser.id,
    type: 'approval_needed',
    title: 'New Reel Ready for Review',
    message: 'A new reel has been generated and needs your approval',
    link: '/approvals',
    isRead: false,
    createdAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-2',
    userId: mockUser.id,
    type: 'post_success',
    title: 'Reel Posted Successfully',
    message: 'Your approved reel was posted to @lifestyle_vibes',
    link: '/accounts/1',
    isRead: false,
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-3',
    userId: mockUser.id,
    type: 'system_alert',
    title: 'High Engagement Alert',
    message: 'Recent post reached 10K views in first hour!',
    link: '/analytics',
    isRead: true,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockAnalytics = [
  {
    id: 1,
    accountId: 1,
    period: 'daily',
    metrics: {
      reach: 12450,
      impressions: 18230,
      engagement: 1560,
      followers: 45230,
      postsCount: 2,
    },
    snapshotDate: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 2,
    accountId: 2,
    period: 'daily',
    metrics: {
      reach: 8920,
      impressions: 13450,
      engagement: 1120,
      followers: 32100,
      postsCount: 1,
    },
    snapshotDate: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
];

export const mockWorkflows = [
  {
    id: 1,
    workflowId: 'workflow-content-gen',
    name: 'Content Generation Pipeline',
    isActive: true,
    lastRunAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    lastRunStatus: 'success',
    executions: {
      total: 145,
      successful: 138,
      failed: 7,
    },
    updatedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: 2,
    workflowId: 'workflow-auto-post',
    name: 'Auto Post to Instagram',
    isActive: true,
    lastRunAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    lastRunStatus: 'success',
    executions: {
      total: 89,
      successful: 86,
      failed: 3,
    },
    updatedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: 3,
    workflowId: 'workflow-analytics-sync',
    name: 'Analytics Data Sync',
    isActive: true,
    lastRunAt: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    lastRunStatus: 'success',
    executions: {
      total: 234,
      successful: 230,
      failed: 4,
    },
    updatedAt: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
  },
  {
    id: 4,
    workflowId: 'workflow-scheduled-check',
    name: 'Scheduled Posts Check',
    isActive: false,
    lastRunAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    lastRunStatus: 'error',
    executions: {
      total: 56,
      successful: 51,
      failed: 5,
    },
    updatedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockLogs = [
  {
    id: 1,
    level: 'info',
    source: 'workflow',
    message: 'Content generation workflow completed successfully',
    details: { workflowId: 'workflow-content-gen', duration: 4500 },
    timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: 2,
    level: 'info',
    source: 'api',
    message: 'Reel approved and queued for posting',
    details: { reelId: 'reel-004', userId: mockUser.id },
    timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 3,
    level: 'warning',
    source: 'auth',
    message: 'Failed login attempt from unauthorized email',
    details: { email: 'unauthorized@example.com', ip: '192.168.1.100' },
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 4,
    level: 'error',
    source: 'workflow',
    message: 'Scheduled posts check failed: Database connection timeout',
    details: { workflowId: 'workflow-scheduled-check', error: 'Connection timeout after 30s' },
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockSettings = [
  {
    id: 1,
    key: 'posting_schedule',
    value: {
      enabled: true,
      timezone: 'America/New_York',
      preferredTimes: ['09:00', '15:00', '21:00'],
    },
    category: 'posting',
    updatedBy: mockUser.id,
    updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 2,
    key: 'auto_approval',
    value: {
      enabled: false,
      minQualityScore: 0.85,
    },
    category: 'workflow',
    updatedBy: mockUser.id,
    updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 3,
    key: 'notifications',
    value: {
      email: true,
      browser: true,
      approvalNeeded: true,
      postSuccess: true,
      postFailed: true,
      systemAlerts: true,
    },
    category: 'notifications',
    updatedBy: mockUser.id,
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
